### ISSUE TITLE
[BUG] Type error in Retrier

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#117]
**Describe the bug**
Looks like there is a type error in Retrier that prevents retry.

**To Reproduce**
View Exam Score

```
flutter: [2022-01-16 12:46:23.083307 | Catcher | INFO] environment: debug
flutter: [2022-01-16 12:46:23.083926 | Catcher | INFO] version: 1.3.0
flutter: [2022-01-16 12:46:23.084478 | Catcher | INFO] appName: DanXi
flutter: [2022-01-16 12:46:23.085046 | Catcher | INFO] buildNumber: 68
flutter: [2022-01-16 12:46:23.085621 | Catcher | INFO] packageName: io.github.danxi-dev.dan-xi
flutter: [2022-01-16 12:46:23.086181 | Catcher | INFO]
flutter: [2022-01-16 12:46:23.086762 | Catcher | INFO] ---------- ERROR ----------
flutter: [2022-01-16 12:46:23.087381 | Catcher | INFO] Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
flutter: [2022-01-16 12:46:23.087911 | Catcher | INFO]
flutter: [2022-01-16 12:46:23.088851 | Catcher | INFO] ------- STACK TRACE -------
flutter: [2022-01-16 12:46:23.089708 | Catcher | INFO] #0      _FutureListener.handleError (dart:async/future_impl.dart:194:7)
flutter: [2022-01-16 12:46:23.090319 | Catcher | INFO] #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
flutter: [2022-01-16 12:46:23.090960 | Catcher | INFO] #2      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
flutter: [2022-01-16 12:46:23.091466 | Catcher | INFO] #3      Future._completeError (dart:async/future_impl.dart:610:5)
flutter: [2022-01-16 12:46:23.092228 | Catcher | INFO] #4      _completeOnAsyncError (dart:async-patch/async_patch.dart:276:13)
flutter: [2022-01-16 12:46:23.092942 | Catcher | INFO] #5      Retrier.tryAsyncWithFix (package:dan_xi/util/retryer.dart)
package:dan_xi/util/retryer.dart:1
flutter: [2022-01-16 12:46:23.093683 | Catcher | INFO] <asynchronous suspension>
flutter: [2022-01-16 12:46:23.094452 | Catcher | INFO]
flutter: [2022-01-16 12:46:23.095250 | Catcher | INFO] ======================================================================
flutter: [2022-01-16 12:46:23.096301 | Catcher | INFO] Report result: true
```

**Comment by w568w** [comment]
The error occurred in (or somewhere similar to this):
```dart
Future<List<ExamScore>?> loadExamScoreRemotely(PersonInfo? info,
        {String? semesterId}) =>
    Retrier.tryAsyncWithFix(
        () => _loadExamScore(semesterId),
        (exception) => UISLoginTool.loginUIS(
            dio!, EXAM_TABLE_LOGIN_URL, cookieJar!, info, true));
```
Maybe it is a result of Dart's type inference that considers `(exception) => UISLoginTool.loginUIS(dio!, EXAM_TABLE_LOGIN_URL, cookieJar!, info, true)` as a function whose return type is `Future<Response>`(which is a subtype of `Future<void>` required by `tryAsyncWithFix`, so it is grammatically correct.) 

But since we call `await tryFix(e).catchError((error, stackTrace) {})`, where the error handler does not return anything, it may cause an error saying `Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type` as you showed above.

If right, The shortest way to solve it is replace `(exception) => UISLoginTool.loginUIS(dio!, EXAM_TABLE_LOGIN_URL, cookieJar!, info, true)` with `(exception) {UISLoginTool.loginUIS(dio!, EXAM_TABLE_LOGIN_URL, cookieJar!, info, true); }`. Try it and test the application again.
