### ISSUE TITLE
[BUG] [Help wanted] 安卓设备上无法修改课评

### ISSUE THREAD

**Issue by HydrogenC** [DanXi-Dev/DanXi#326]
**描述 Bug**
电脑端上课评修改功能工作正常，提交后显示请求成功，课评也成功更改。  
安卓端提交修改后app不发送请求。  
来自社区反馈，机型未知。但在本人的小米K60上成功复现此问题，尚不知该问题是否影响所有机型。

**复现步骤**
复现该 Bug 的步骤：
1. 找到自己发送的课评
2. 修改并提交

**截图**
无

**系统信息**
 - 设备型号：Xiaomi K60
 - 系统版本：Android 13
 - 旦夕版本（见「设置-关于本应用」）：1.4.1

**Comment by kooWZ** [comment]
```
E/flutter (10117): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (10117): At this point the state of the widget's element tree is no longer stable.
E/flutter (10117): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (10117): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4558:9)
E/flutter (10117): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4572:6)
E/flutter (10117): #2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4591:12)
E/flutter (10117): #3      Localizations.of (package:flutter/src/widgets/localizations.dart:529:48)
E/flutter (10117): #4      S.maybeOf (package:dan_xi/generated/l10n.dart:50:26)
E/flutter (10117): #5      S.of (package:dan_xi/generated/l10n.dart:43:24)
E/flutter (10117): #6      CourseReviewEditor.modifyReply (package:dan_xi/page/danke/course_review_editor.dart:190:24)
E/flutter (10117): <asynchronous suspension>
E/flutter (10117): #7      ModifyMenuWidgetState.build.<anonymous closure> (package:dan_xi/widget/danke/course_review_widget.dart:334:15)
E/flutter (10117): <asynchronous suspension>
```

**Comment by w568w** [comment]
> `At this point the state of the widget's element tree is no longer stable.`

看起来又是个 `context` 误用的问题……

**Comment by w568w** [comment]
原因基本确定是 Android 设备上进入新页面后，输入法弹起，导致原页面 `CourseGroupDetail` 触发 rebuild。而由于页面内大量在 `build` 方法中创建 `Future`，导致控件树一定刷新（解释：每次 `build()` 中都重新调用了 async 方法以创建 `Future`。任何两次创建的 `Future` 都是**不同的对象**。新的 `Future` 作为参数被传递给 `FutureWidget` 和 `PagedListView`，从而导致了这两者的 rebuild），继而导致了原来的 `ModifyMenuWidget` 被销毁。然而 Editor 提交时引用了 `ModifyMenuWidget` 的 context，所以它使用了已经无效的 context，产生错误。

最合理的解决方法是 **build 中根本就不应该创建 Future**。
