### ISSUE TITLE
[BUG] 在 Android 14 上无法初始化 MiPush SDK：Didn't find class "com.android.id.impl.IdProviderImpl"

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#437]
**描述 Bug**
来自 <https://github.com/DanXi-Dev/DanXi/pull/433#issuecomment-2481312396>。

在 Android 14 上，应用启动时出现下列错误输出：

```
W/XMPush-7670( 7670): [Tid:8078] sdk_version = 5_7_8-C
V/XMPush-7670( 7670): [Tid:8078] loadClass fail hasContext= true, errMsg = com.android.id.impl.IdProviderImpl
V/XMPush-7670( 7670): [Tid:8078] miui load class error
V/XMPush-7670( 7670): java.lang.ClassNotFoundException: loadClass fail 
V/XMPush-7670( 7670): 	at com.xiaomi.push.r.a(SourceFile:170)
V/XMPush-7670( 7670): 	at com.xiaomi.push.au.a(SourceFile:46)
V/XMPush-7670( 7670): 	at com.xiaomi.push.au.<init>(SourceFile:41)
V/XMPush-7670( 7670): 	at com.xiaomi.push.av.a(SourceFile:29)
V/XMPush-7670( 7670): 	at com.xiaomi.push.aw.<init>(SourceFile:31)
V/XMPush-7670( 7670): 	at com.xiaomi.push.aw.a(SourceFile:40)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient.initialize(SourceFile:228)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient.access$100(SourceFile:63)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient$1.run(SourceFile:169)
V/XMPush-7670( 7670): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
V/XMPush-7670( 7670): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
V/XMPush-7670( 7670): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
V/XMPush-7670( 7670): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
V/XMPush-7670( 7670): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
V/XMPush-7670( 7670): 	at java.lang.Thread.run(Thread.java:1012)
V/XMPush-7670( 7670): Caused by: java.lang.ClassNotFoundException: com.android.id.impl.IdProviderImpl
V/XMPush-7670( 7670): 	at java.lang.Class.classForName(Native Method)
V/XMPush-7670( 7670): 	at java.lang.Class.forName(Class.java:607)
V/XMPush-7670( 7670): 	at java.lang.Class.forName(Class.java:512)
V/XMPush-7670( 7670): 	at com.xiaomi.push.r.a(SourceFile:167)
V/XMPush-7670( 7670): 	... 14 more
V/XMPush-7670( 7670): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.id.impl.IdProviderImpl" on path: DexPathList[[zip file "/data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/base.apk"],nativeLibraryDirectories=[/data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/lib/arm64, /data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
V/XMPush-7670( 7670): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
V/XMPush-7670( 7670): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
V/XMPush-7670( 7670): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
V/XMPush-7670( 7670): 	... 18 more
```

在升级 MiPush SDK 版本到最新的 6.0.1 之后，该问题也没有解决。需要调查问题的原因，以及该问题是否影响正常推送。

**复现步骤**
复现该 Bug 的步骤：
1. 从 main 分支编译应用，在 Android 14+ 设备上运行；
2. 查看启动时的日志输出，发生上述错误。

**Comment by w568w** [comment]
在 Android 12 模拟器设备上的错误日志：

```
W/XMPush-4589( 4589): [Tid:45] sdk_version = 6_0_1-C
V/XMPush-4589( 4589): [Tid:45] sdk_version = 6_0_1-C
W/XMPush-4589( 4589): [Tid:40] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:40] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] loadClass fail hasContext= true, errMsg = com.bun.miitmdid.core.JLibrary
V/XMPush-4589( 4589): [Tid:45] mdid:check error java.lang.ClassNotFoundException: loadClass fail 
V/XMPush-4589( 4589): [Tid:45] create id manager is: 0
W/XMPush-4589( 4589): [Tid:45] register invalid, aid=false;atn=false;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] register invalid, aid=false;atn=false;rid=false;rse=false
W/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] Don't send message before initialization succeeded!
V/XMPush-4589( 4589): [Tid:45] locale.default.country = 
V/XMPush-4589( 4589): [Tid:45] loadClass fail hasContext= false, errMsg = miui.os.Build
W/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] Don't send message before initialization succeeded!
W/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] register invalid, aid=true;atn=true;rid=false;rse=false
V/XMPush-4589( 4589): [Tid:45] Don't send message before initialization succeeded!
```

**Comment by w568w** [comment]
根据反编译源代码和 [相关 SDK](https://github.com/gzu-liyujiang/Android_CN_OAID/blob/master/library/src/main/java/com/github/gzuliyujiang/oaid/impl/XiaomiImpl.java) 确定，`com.android.id.impl.IdProviderImpl` 是小米设备上 OAID 定义的类，在国外类原生 ROM 和虚拟机 ROM 中可能不存在。该类的报错已被 catch，也不影响正常初始化。判断该问题并不存在。
